spring.application.name=EnterpriseAppsLaureGraceLokiyo

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port=8081

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=8bab2e3e89ed6e
spring.mail.password=c8250b183df2a7

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true